data:
  patch_size: [64, 64, 64]
  augmentation:
    rotation: False
    random_center: True

model:
  model_name: "Unet"
  mixed_precision: true
  output_channels: 3
  kernel_size: 5
  last_activation: "softmax"
  # n_features: [12, 24, 48, 96, 192]
  n_features: [4, 8, 16, 32, 64]
  # n_features: [2, 4, 8, 16, 32]
  # n_features: [1, 1, 1, 1, 1]
  compile:
    optimizer: "adam"
    learning_rate: 0.001
    # lr_scheduler:
    #   initial_learning_rate: 0.01
    #   decay_steps: 10000
    #   decay_rate: 0.9
    loss: "dsc"

training:
  epochs: 200
  batch_size: 2
